version: '3.8'

services:
  app:
    build:
      context: .
    image: maliedvp/germundat_db:latest
    container_name: germundat_app
    ports:
      - "888:888"      # SSH port
    volumes:
      - .:/home/ubuntu/workspace   # mount your project dir in the container
    depends_on:
      - db
    environment:
      # if your Dockerfile uses these defaults you can override here
      SSH_PORT: 888
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: gdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme

  db:
    image: postgres:14
    container_name: germundat_db
    restart: always
    ports:
      - "5432:5432"   # expose Postgres on localhost:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: gdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
